version: '3'

services:

  mysql-development:
    image: mysql:8.0.17
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: mydb
        MYSQL_USER: user
        MYSQL_PASSWORD: pass
    ports:
      - "3308:3306"