version: '3'

services:
  mysql-development:
    image: mysql:8.0.17
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: mydb
        MYSQL_USER: user
        MYSQL_PASSWORD: pass
    ports:
      - 3310:3306

  authservice:
    image: authservice
    build: .
    command: java -jar JavaCoreServer.jar --authservice 192.168.99.100 3310
    ports:
      - 8081:8081

  vmservice:
    image: vmservice
    build: .
    command: java -jar JavaCoreServer.jar --vmservice 192.168.99.100 3310
    ports:
    - 1234:8080